### ISSUE TITLE
write css and html template that will be used by all the participants 

### ISSUE THREAD

**Issue by Chaitya62** [KJSCE-Codecell/Javascript-notes#10]
We'll only explain and write js from scratch rest will be reused

**Comment by Chaitya62** [comment]
@Freelancer-98  @karan28598 @rajshah80266  maybe one of you can take this up

**Comment by karan28598** [comment]
[https://github.com/karan28598/Canvas-Draw/blob/master/index.html](url)

**Comment by Chaitya62** [comment]
@karan28598  Page not found!

**Comment by inishchith** [comment]
@Chaitya62 [here](https://github.com/karan28598/Canvas-Draw/blob/master/index.html)
